name: Release

env:
  NODE_VERSION: 19.5.0

on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Show tag
        run: |
          git describe --tags --abbrev=0
          echo "TAG=$TAG" >> $GITHUB_ENV
        env:
          TAG: git describe --tags --abbrev=0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run prdbuild:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./electron-build/ai-blog-assistant-v*-Setup.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Show tag
        run: |
          git describe --tags --abbrev=0
          echo "TAG=$TAG" >> $GITHUB_ENV
        env:
          TAG: git describe --tags --abbrev=0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run prdbuild:mac
      - name: Create release with artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./electron-build/ai-blog-assistant-v*-Setup.pkg
